config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :valentines

   root 'valentines#index'

end

app/models/user.rb
class User < ActiveRecord::Base


end

app/models/valentine.rb
class Valentine < ActiveRecord::Base


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

end

app/controllers/valentines_controller.rb
class ValentinesController < ApplicationController

  def index
    @valentines = Valentine.all
  end

  def new
    @valentine = Valentine.new
  end

  def create
    @valentine = Valentine.new(valentine_params)
      if @valentine.save
        redirect_to root_url
      else
        render :new
      end
  end
  

  private

  def valentine_params
    params.require(:valentine).permit(:name, :message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Valentine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/users/index.html.erb
hi

app/views/users/index.html.erb
yay

app/views/valentines/index.html.erb
<h2><%= link_to image_tag("heart.png", class: "img-responsive"), new_valentine_path  %></h2>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Valentines Message</th>
    </tr>
  </thead>
  <tbody>
    <% @valentines.each do |valentine| %>
    <tr>
      <td> <%= valentine.name %> </td>
      <td> <%= valentine.message %> </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/valentines/new.html.erb
<br>
<br>
<h3>Deliver your Valentine message</h3>
<br>

<%= form_for(@valentine, html: {class: "form-horizontal"}) do |f| %>


<form class="form-horizontal">
  <div class="form-group">
      <%= f.label :name, class: "control-label col-md-2" %>
    <div class="form-controls col-md-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
      <%= f.label :message, class: "control-label col-md-2" %>
    <div class="form-controls col-md-4">
      <%= f.text_field :message, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-4">
      <%= f.submit class: "btn btn-danger"%>
      <%= link_to "Cancel", valentines_path, class: "btn btn-default"%>
    </div>
  </div>
</form>

<% end %>

app/views/valentines/show.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Valentines Message</th>
    </tr>
  </thead>
  <tbody>
    <% @valentines.each do |valentine| %>
    <tr>
      <td> <%= valentine.name %> </td>
      <td> <%= valentine.message %> </td>
    </tr>
    <% end %>
  </tbody>
</table>